### ISSUE TITLE
Release for GHC 8.10

### ISSUE THREAD

**Issue by dbeacham** [leftaroundabout/trivial-constraint#9]
Is it possible to get version bump and release for 8.10?

**Comment by leftaroundabout** [comment]
Sure. Is the current `master` version ok?

**Comment by dbeacham** [comment]
Yeah - all compiles fine here.

#8 has fixed the problems I was having.

**Comment by leftaroundabout** [comment]
http://hackage.haskell.org/package/trivial-constraint-0.7.0.0
